# Generated by Django 5.2.1 on 2026-04-03 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fiancical_records',
            new_name='financial_records',
        ),
    ]
