# Generated by Django 5.2.1 on 2026-04-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_fiancical_records_financial_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_records',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
